definitions:
  dozenChairs_internal_dto.AccessTokenResponse:
    properties:
      accessToken:
        type: string
    type: object
  dozenChairs_internal_dto.AuthResponse:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
      user:
        $ref: '#/definitions/dozenChairs_internal_dto.UserResponse'
    type: object
  dozenChairs_internal_dto.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  dozenChairs_internal_dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dozenChairs_internal_dto.RegisterRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 3
        type: string
    required:
    - email
    - password
    - username
    type: object
  dozenChairs_internal_dto.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
  dozenChairs_internal_models.Image:
    properties:
      created_at:
        type: string
      filename:
        type: string
      id:
        type: string
      product_id:
        type: string
      url:
        type: string
    type: object
  dozenChairs_internal_models.IncludeItem:
    properties:
      productId:
        type: string
      quantity:
        type: integer
    required:
    - productId
    - quantity
    type: object
  dozenChairs_internal_models.Product:
    properties:
      attributes:
        additionalProperties: true
        type: object
      category:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        description: можно добавить `uuid4` при необходимости
        type: string
      images:
        items:
          $ref: '#/definitions/dozenChairs_internal_models.Image'
        type: array
      inStock:
        type: boolean
      includes:
        description: только для sets
        items:
          $ref: '#/definitions/dozenChairs_internal_models.IncludeItem'
        type: array
      oldPrice:
        minimum: 0
        type: integer
      price:
        minimum: 0
        type: integer
      slug:
        description: можно добавить custom slug-валидацию
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      type:
        allOf:
        - $ref: '#/definitions/dozenChairs_internal_models.ProductType'
        enum:
        - product
        - set
      unitCount:
        minimum: 0
        type: integer
      updatedAt:
        type: string
    required:
    - category
    - id
    - slug
    - title
    - type
    type: object
  dozenChairs_internal_models.ProductType:
    enum:
    - product
    - set
    type: string
    x-enum-varnames:
    - TypeProduct
    - TypeSet
  dozenChairs_pkg_httphelper.APIResponse:
    properties:
      data: {}
      error: {}
      meta: {}
    type: object
info:
  contact: {}
paths:
  /api/v1//images/{id}:
    delete:
      parameters:
      - description: Image ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Удалить изображение по ID
      tags:
      - Images
  /api/v1//products/{product_id}/images:
    get:
      parameters:
      - description: ID или slug товара
        in: path
        name: product_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dozenChairs_internal_models.Image'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Получить изображения по товару
      tags:
      - Images
  /api/v1//upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: ID товара
        in: formData
        name: product_id
        required: true
        type: string
      - description: Файлы изображений (можно несколько)
        in: formData
        name: images
        required: true
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/dozenChairs_internal_models.Image'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Загрузить изображения для продукта
      tags:
      - Images
  /api/v1/auth/callback/{provider}:
    get:
      description: Обрабатывает код, полученный от VK, Google или Yandex, и возвращает
        JWT токены
      parameters:
      - description: OAuth-провайдер
        enum:
        - google
        - yandex
        - vk
        in: path
        name: provider
        required: true
        type: string
      - description: Код от OAuth-провайдера
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      summary: Callback от OAuth-провайдера
      tags:
      - auth
  /api/v1/auth/login:
    post:
      consumes:
      - application/json
      description: Принимает email и пароль, возвращает access и refresh токены
      parameters:
      - description: Данные авторизации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      summary: Авторизация пользователя
      tags:
      - auth
  /api/v1/auth/logout:
    post:
      consumes:
      - application/json
      description: Удаляет refresh токен из хранилища и куки
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      summary: Выход пользователя
      tags:
      - auth
  /api/v1/auth/me:
    get:
      description: Возвращает профиль пользователя по access токену
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Получить информацию о текущем пользователе
      tags:
      - auth
  /api/v1/auth/oauth/{provider}:
    get:
      description: Редиректит пользователя на страницу авторизации Google, VK или
        Yandex
      parameters:
      - description: OAuth-провайдер
        enum:
        - google
        - yandex
        - vk
        in: path
        name: provider
        required: true
        type: string
      produces:
      - application/json
      responses:
        "307":
          description: Redirect
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      summary: Перенаправление на OAuth-провайдера
      tags:
      - auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Обновляет access токен по refresh токену из куки
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.AccessTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      summary: Обновление access токена
      tags:
      - auth
  /api/v1/auth/register:
    post:
      consumes:
      - application/json
      description: Создаёт нового пользователя и возвращает access и refresh токены
      parameters:
      - description: Данные регистрации
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.AuthResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/dozenChairs_internal_dto.ErrorResponse'
      summary: Регистрация пользователя
      tags:
      - auth
  /api/v1/categories:
    get:
      description: Возвращает все уникальные категории товаров
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список категорий
      tags:
      - Products
  /api/v1/products:
    get:
      description: Возвращает список товаров или наборов. Доступна фильтрация по типу,
        категории и наличию, а также сортировка по цене и дате создания.
      parameters:
      - description: Тип товара (product или set)
        in: query
        name: type
        type: string
      - description: Категория
        in: query
        name: category
        type: string
      - description: Есть в наличии
        in: query
        name: inStock
        type: boolean
      - description: Сортировка (price или createdAt)
        in: query
        name: sort
        type: string
      - description: Лимит на страницу (по умолчанию 20)
        in: query
        name: limit
        type: integer
      - description: Смещение (по умолчанию 0)
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dozenChairs_internal_models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список товаров
      tags:
      - Products
    post:
      consumes:
      - application/json
      description: Только для админов. Создаёт новый товар или набор. У набора нужно
        указать поле `includes`, а у обычного товара — `unitCount` и `attributes`.
      parameters:
      - description: Данные нового товара или набора
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      security:
      - BearerAuth: []
      summary: Создать товар
      tags:
      - Products
  /api/v1/products/{slug}:
    delete:
      description: Только для админов. Удаляет товар по slug. При удалении набора
        удаляется только сам набор, не включённые в него товары.
      parameters:
      - description: Slug товара
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      security:
      - BearerAuth: []
      summary: Удалить товар
      tags:
      - Products
    get:
      description: Возвращает один товар по его уникальному slug. Включает изображения,
        атрибуты и, при типе set — включённые товары.
      parameters:
      - description: Slug товара
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.Product'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить товар по slug
      tags:
      - Products
    put:
      consumes:
      - application/json
      description: Только для админов. Обновляет данные товара по slug. Все поля можно
        изменить, включая изображения, состав набора и атрибуты.
      parameters:
      - description: Slug товара
        in: path
        name: slug
        required: true
        type: string
      - description: Обновлённые данные товара
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      security:
      - BearerAuth: []
      summary: Обновить товар
      tags:
      - Products
  /api/v1/products/new:
    get:
      description: Возвращает список недавно добавленных товаров — либо последние
        N штук, либо за последние X дней
      parameters:
      - description: Лимит (по умолчанию 10)
        in: query
        name: limit
        type: integer
      - description: За сколько последних дней брать товары
        in: query
        name: days
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dozenChairs_internal_models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список новинок
      tags:
      - Products
  /api/v1/sets:
    get:
      description: Возвращает все товары типа set. Наборы включают список вложенных
        товаров (`includes`).
      parameters:
      - description: Есть в наличии
        in: query
        name: inStock
        type: boolean
      - description: Сортировка (price или createdAt)
        in: query
        name: sort
        type: string
      - description: Лимит на страницу
        in: query
        name: limit
        type: integer
      - description: Смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dozenChairs_internal_models.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список наборов
      tags:
      - Sets
  /api/v1/sets/{slug}:
    get:
      description: Возвращает товар типа set по его slug. Если товар не является набором,
        будет возвращена ошибка.
      parameters:
      - description: Slug набора
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить набор по slug
      tags:
      - Sets
swagger: "2.0"
