basePath: /
definitions:
  dozenChairs_internal_models.Chair:
    properties:
      attributes:
        $ref: '#/definitions/dozenChairs_internal_models.ChairAttributes'
      category:
        description: всегда "chair"
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        type: string
      images:
        items:
          type: string
        type: array
      inStock:
        type: boolean
      oldPrice:
        type: integer
      price:
        type: integer
      slug:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      type:
        description: всегда "product"
        type: string
      unitCount:
        type: integer
      updatedAt:
        type: string
    type: object
  dozenChairs_internal_models.ChairAttributes:
    properties:
      color:
        type: string
      colorFrame:
        type: string
      colorPillow:
        type: string
      material:
        type: string
      materialFrame:
        type: string
      materialPillow:
        type: string
      totalHeight:
        type: integer
      width:
        type: integer
    type: object
  dozenChairs_internal_models.User:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      full_name:
        type: string
      id:
        type: integer
      phone:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
  internal_handlers.LoginRequest:
    properties:
      email_or_username:
        type: string
      password:
        type: string
    type: object
  internal_handlers.LoginResponse:
    properties:
      token:
        type: string
      user: {}
    type: object
  internal_handlers.RegisterRequest:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: API для магазина мебели
  title: DozenChairs API
  version: "1.0"
paths:
  /chairs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dozenChairs_internal_models.Chair'
            type: array
      summary: Получить все стулья
      tags:
      - chairs
    post:
      consumes:
      - application/json
      parameters:
      - description: Стул
        in: body
        name: chair
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_models.Chair'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.Chair'
      summary: Создать стул
      tags:
      - chairs
  /chairs/{slug}:
    delete:
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "404":
          description: Не найден
          schema:
            type: string
      summary: Удалить стул по slug
      tags:
      - chairs
    get:
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.Chair'
        "404":
          description: Не найден
          schema:
            type: string
      summary: Получить стул по slug
      tags:
      - chairs
    patch:
      consumes:
      - application/json
      parameters:
      - description: Slug
        in: path
        name: slug
        required: true
        type: string
      - description: Обновляемые данные
        in: body
        name: chair
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_models.Chair'
      responses:
        "204":
          description: No Content
          schema:
            type: string
        "400":
          description: Некорректные данные
          schema:
            type: string
        "404":
          description: Не найден
          schema:
            type: string
      summary: Обновить стул по slug
      tags:
      - chairs
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для логина
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_handlers.LoginResponse'
        "401":
          description: Неверные учетные данные
          schema:
            type: string
      summary: Логин пользователя
      tags:
      - auth
  /profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.User'
        "401":
          description: Не авторизован
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Получение профиля пользователя
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для регистрации
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/internal_handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dozenChairs_internal_models.User'
        "400":
          description: Некорректный запрос
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - auth
schemes:
- http
swagger: "2.0"
