basePath: /
definitions:
  handlers.LoginRequest:
    properties:
      email_or_username:
        type: string
      password:
        type: string
    type: object
  handlers.LoginResponse:
    properties:
      token:
        type: string
      user: {}
    type: object
  handlers.RegisterRequest:
    properties:
      address:
        type: string
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
  models.User:
    properties:
      address:
        type: string
      created_at:
        type: string
      email:
        type: string
      email_verified:
        type: boolean
      full_name:
        type: string
      id:
        type: integer
      phone:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: API для магазина мебели
  title: DozenChairs API
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для логина
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.LoginResponse'
        "401":
          description: Неверные учетные данные
          schema:
            type: string
      summary: Логин пользователя
      tags:
      - auth
  /profile:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "401":
          description: Не авторизован
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Получение профиля пользователя
      tags:
      - auth
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: Данные для регистрации
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Некорректный запрос
          schema:
            type: string
      summary: Регистрация пользователя
      tags:
      - auth
schemes:
- http
swagger: "2.0"
