basePath: /api/v1
definitions:
  dozenChairs_internal_models.IncludeItem:
    properties:
      productId:
        type: string
      quantity:
        type: integer
    required:
    - productId
    - quantity
    type: object
  dozenChairs_internal_models.Product:
    properties:
      attributes:
        additionalProperties: true
        type: object
      category:
        type: string
      createdAt:
        type: string
      description:
        type: string
      id:
        description: можно добавить `uuid4` при необходимости
        type: string
      images:
        items:
          type: string
        type: array
      inStock:
        type: boolean
      includes:
        description: только для sets
        items:
          $ref: '#/definitions/dozenChairs_internal_models.IncludeItem'
        type: array
      oldPrice:
        minimum: 0
        type: integer
      price:
        minimum: 0
        type: integer
      slug:
        description: можно добавить custom slug-валидацию
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      type:
        allOf:
        - $ref: '#/definitions/dozenChairs_internal_models.ProductType'
        enum:
        - product
        - set
      unitCount:
        minimum: 0
        type: integer
      updatedAt:
        type: string
    required:
    - category
    - id
    - slug
    - title
    - type
    type: object
  dozenChairs_internal_models.ProductType:
    enum:
    - product
    - set
    type: string
    x-enum-varnames:
    - TypeProduct
    - TypeSet
  dozenChairs_pkg_httphelper.APIResponse:
    properties:
      data: {}
      error: {}
      meta: {}
    type: object
host: localhost:8080
info:
  contact:
    email: support@dozenchairs.io
    name: API Support
  description: REST API for managing chairs, tables and sets
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: DozenChairs API
  version: "1.0"
paths:
  /categories:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список категорий
      tags:
      - Products
  /products:
    get:
      parameters:
      - description: Тип товара (product или set)
        in: query
        name: type
        type: string
      - description: Категория
        in: query
        name: category
        type: string
      - description: Есть в наличии
        in: query
        name: inStock
        type: boolean
      - description: Сортировка (price или createdAt)
        in: query
        name: sort
        type: string
      - description: Лимит на страницу
        in: query
        name: limit
        type: integer
      - description: Смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список товаров
      tags:
      - Products
    post:
      consumes:
      - application/json
      parameters:
      - description: Product JSON
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_models.Product'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Создать товар
      tags:
      - Products
  /products/{slug}:
    delete:
      parameters:
      - description: Slug товара
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Удалить товар по slug
      tags:
      - Products
    get:
      parameters:
      - description: Slug товара
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить товар по slug
      tags:
      - Products
    put:
      consumes:
      - application/json
      parameters:
      - description: Slug товара
        in: path
        name: slug
        required: true
        type: string
      - description: Обновленные данные товара
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/dozenChairs_internal_models.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Обновить товар по slug
      tags:
      - Products
  /sets:
    get:
      parameters:
      - description: Есть в наличии
        in: query
        name: inStock
        type: boolean
      - description: Сортировка (price или createdAt)
        in: query
        name: sort
        type: string
      - description: Лимит на страницу
        in: query
        name: limit
        type: integer
      - description: Смещение
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить список наборов
      tags:
      - Sets
  /sets/{slug}:
    get:
      parameters:
      - description: Slug набора
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dozenChairs_pkg_httphelper.APIResponse'
      summary: Получить набор по slug
      tags:
      - Sets
swagger: "2.0"
